controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

entity_show:
    path: /{entity}/{slug}
    controller: App\Controller\EntityShowController::show
